# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160227134832 on 2016-02-28 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('position', models.IntegerField()),
            ],
        ),
    ]
